# Generated by Django 5.2.13 on 2026-04-13 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='servicio',
        ),
        migrations.AddField(
            model_name='appointment',
            name='servicios',
            field=models.ManyToManyField(related_name='appointments', to='core.service'),
        ),
    ]
